# Generated by Django 6.0.3 on 2026-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeditem',
            name='label',
            field=models.CharField(blank=True, help_text='Optional batch or serial label', max_length=200),
        ),
    ]
