# Generated by Django 6.0.3 on 2026-03-28 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_alter_userprofile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturing_plans', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_plan', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sequence_order', models.PositiveIntegerField(default=0)),
                ('sop_document', models.FileField(blank=True, null=True, upload_to='designer/sops/')),
                ('sop_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='designer.manufacturingplan')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='QualityChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('expected_result', models.CharField(blank=True, max_length=300)),
                ('result_status', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail'), ('na', 'Not Applicable')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checklist', to='designer.manufacturingstep')),
            ],
        ),
        migrations.CreateModel(
            name='StepMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('specification', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('supplier_notes', models.TextField(blank=True)),
                ('storage_location', models.CharField(blank=True, help_text="Current location, e.g. 'Warehouse A, Shelf B3'", max_length=300)),
                ('storage_conditions', models.CharField(blank=True, help_text="Special requirements, e.g. 'Keep dry, max 25C'", max_length=300)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='designer.manufacturingstep')),
            ],
        ),
        migrations.CreateModel(
            name='StepDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='designer.manufacturingstep')),
                ('to_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='designer.manufacturingstep')),
            ],
            options={
                'verbose_name_plural': 'Step dependencies',
                'unique_together': {('from_step', 'to_step')},
            },
        ),
    ]
