# Generated by Django 6.0.3 on 2026-03-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingstep',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manufacturingstep',
            name='execution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manufacturingstep',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
