# Generated by Django 6.0.3 on 2026-03-27 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g., 304 Stainless Steel Bracket Assembly', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('step_1_programming', models.BooleanField(default=False)),
                ('step_2_cutting', models.BooleanField(default=False)),
                ('step_3_forming', models.BooleanField(default=False)),
                ('step_4_joining', models.BooleanField(default=False)),
                ('step_5_delivery', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.order')),
            ],
        ),
    ]
