# Generated by Django 6.0.3 on 2026-03-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('manufacturer', 'Manufacturer'), ('designer', 'Designer')], default='customer', max_length=20),
        ),
    ]
