# Generated by Django 6.0.3 on 2026-03-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='step_context',
            field=models.CharField(blank=True, help_text='The flowchart step clicked', max_length=255, null=True),
        ),
    ]
