# Generated by Django 6.0.3 on 2026-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chatmessage_attachment_chatmessage_step_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('customer', 'Customer'), ('manufacturer', 'Manufacturer'), ('designer', 'Designer'), ('warehouse', 'Warehouse')], default='customer', max_length=20),
        ),
    ]
